name: attcalci
description: CollegeBud - The Ultimate College Companion
publish_to: 'none'
version: 1.2.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  http: ^1.2.0
  
  # Parsing
  html: ^0.15.4
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  flutter_secure_storage: ^9.0.0
  
  # UI
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.4
  uuid: ^4.5.2
  workmanager: ^0.9.0
  flutter_local_notifications: ^17.2.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21

